if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'ABOVE_GROUND_LIVING_AREA'
'BLDG_TYPE'
'BSMT_FINISH_SQR_FT'
'BSMT_UNFINISH_SQR_FT'
'EXTERIOR_QUALITY'
'FIREPLACES'
'FOUNDATION'
'GARAGE_AREA'
'GARAGE_CARS'
'HEATING_QC'
'LOT_AREA'
'LOT_SHAPE'
'NUMBER_BEDROOM_ABOVE_GROUND'
'OPEN_PORCH_SQR_FT'
'OVERALL_CONDITION'
'OVERALL_QUALITY'
'TOTAL_BSMT_SQR_FT'
'VENEER_AREA_OF_EXTERIOR_WALL'
'YEAR_BUILT'
'YEAR_REMODEL'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg: Rejected using stepwise selection";
end;
end;
